module.exports = {
    // Keys and other mathematical constants
    KEY_ESC: 27,
    KEY_ENTER: 13,            
    KEY_LEFT: 65,
    KEY_UP: 87,
    KEY_RIGHT: 68,
    KEY_DOWN: 83,
    KEY_SHIFT: 16,
    borderDraw: true,
    onShowPeleng:true,
    onShowPlayers:true,    
    
    // Canvas

    userScreenWidth:1600,
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,

    realWidth: window.innerWidth,
    realHeight: window.innerHeight,
    gameWidth: 0,
    gameHeight: 0,
    xoffset: -0,
    yoffset: -0,
    graphCtx:0,
    meterPerPixel:1,
    tecAngle:0,
    pelengs : [],
    findFox: [],
    alfaCh:0.5,
    totalFoxes:0,
    indexID:-1,
    indexFox:-1,
    gameStart: false,
    toFinish:false,
    disconnected: false,
    leftButtonPress: false,    
    player:{},
    target:{},
    died: false,
    resize:false,    
    startPingTime: 0,
    toggleMassState: 0,
    backgroundColor: '#fefefe',
    lineColor: 'rgba(0,200,0,0.5)',
    borderColor:'rgba(50,50,50,1)',
    framePerSec: 5,
    mainX:0,
    mainY:0,

};
